In [59]:
import numpy as np
import pandas as pd

In [60]:
inputt = np.arange(15)
inputt = inputt.reshape(5, 3).T
print(inputt)

[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]


In [61]:
w1 = np.ones((5, 4)) * np.sqrt(1 / 5)
b1 = np.zeros((1, 4)) 

print(w1)
print(b1)

[[0.4472136 0.4472136 0.4472136 0.4472136]
 [0.4472136 0.4472136 0.4472136 0.4472136]
 [0.4472136 0.4472136 0.4472136 0.4472136]
 [0.4472136 0.4472136 0.4472136 0.4472136]
 [0.4472136 0.4472136 0.4472136 0.4472136]]
[[0. 0. 0. 0.]]


In [62]:
def relu(x):
    return np.maximum(0, x)

In [63]:
z1 = inputt.dot(w1) + b1
a1 = relu(z1)
print(z1)

[[13.41640786 13.41640786 13.41640786 13.41640786]
 [15.65247584 15.65247584 15.65247584 15.65247584]
 [17.88854382 17.88854382 17.88854382 17.88854382]]


In [64]:
w2 = np.ones((4, 2)) * np.sqrt(1 / 2)
b2 = np.zeros((1,2))

In [65]:
z2 = a1.dot(w2) + b2
a2 = relu(z2)
print(a2)

[[37.94733192 37.94733192]
 [44.27188724 44.27188724]
 [50.59644256 50.59644256]]


In [66]:
w3 = np.ones((2, 1)) * np.sqrt(1 / 5)
b3 = 0

In [67]:
def softmax(x):
    x = x - np.max(x, axis=0, keepdims=True)  # Normalize to prevent overflow
    e = np.exp(x)
    return e / np.sum(e, axis=0, keepdims=True)


In [68]:
z3 = a2.dot(w3) + b3
a3 = softmax(z3)
print(a3)

[[1.21618317e-05]
 [3.48128496e-03]
 [9.96506553e-01]]


In [69]:
realY = np.array([0.1, 0.3, .6])
realY = realY.reshape(-1, 1)

In [70]:
def Loss(x, realY):
    loss = -np.sum(realY * np.log(x + 1e-8))
    return loss

In [71]:
def reluDerivative(x):
    return (x > 0).astype(float)

In [72]:
def backProp(a3, w3, a2, z2, a1, w2, z1, inputt, realY):
    dz3 = a3 - realY  # 3x1
    dw3 = a2.T.dot(dz3) # 2x1
    db3 = np.sum(dz3, axis=0, keepdims=True)    # 1x1
    da2 = dz3.dot(w3.T) # 3x2
    dz2 = da2 * reluDerivative(z2)  # 3x2
    
    dw2 = a1.T.dot(dz2) # 
    db2 = np.sum(dz2, axis=0, keepdims=True)

    da1 = dz2.dot(w2.T)
    dz1 = da1 * reluDerivative(z1)
    dw1 = inputt.T.dot(dz1)
    db1 = np.sum(dz1, axis=0, keepdims=True)

    return dw3, db3, dw2, db2, dw1, db1

In [73]:
# dw3, db3, dw2, db2, dw1, db1 = backProp(a3, w3, a2, z2, a1, w2, z1, inputt, realY)

# print(dw3)
# print(db3)
# print(dw2)
# print(db2)
# print(dw1)
# print(db1)

In [74]:
iterations = 17
alpha = 0.05
print("This is w3: " ,w3)
print(b3)
print(w2)
print(b2)
print(w1)
print(b1)

print("updations")
for i in range(iterations):

    z1 = inputt.dot(w1) + b1
    a1 = relu(z1)

    z2 = a1.dot(w2) + b2
    a2 = relu(z2)

    z3 = a2.dot(w3) + b3
    a3 = softmax(z3)  
    print(a3)

    dw3, db3, dw2, db2, dw1, db1 = backProp(a3, w3, a2, z2, a1, w2, z1, inputt, realY)

    w3 = w3 - alpha * dw3
    b3 = b3 - alpha * db3
    w2 = w2 - alpha * dw2
    b2 = b2 - alpha * db2
    w1 = w1 - alpha * dw1
    b1 = b1 - alpha * db1

print("This is w3: ", w3.shape)
print(b3)
print(w2)
print(b2)
print(w1)
print(b1)

This is w3:  [[0.4472136]
 [0.4472136]]
0
[[0.70710678 0.70710678]
 [0.70710678 0.70710678]
 [0.70710678 0.70710678]
 [0.70710678 0.70710678]]
[[0. 0.]]
[[0.4472136 0.4472136 0.4472136 0.4472136]
 [0.4472136 0.4472136 0.4472136 0.4472136]
 [0.4472136 0.4472136 0.4472136 0.4472136]
 [0.4472136 0.4472136 0.4472136 0.4472136]
 [0.4472136 0.4472136 0.4472136 0.4472136]]
[[0. 0. 0. 0.]]
updations
[[1.21618317e-05]
 [3.48128496e-03]
 [9.96506553e-01]]
[[0.00103993]
 [0.03171535]
 [0.96724473]]
[[0.026238  ]
 [0.14726078]
 [0.82650122]]
[[0.12987341]
 [0.27744186]
 [0.59268472]]
[[0.10931267]
 [0.26212549]
 [0.62856184]]
[[0.1196317 ]
 [0.27018096]
 [0.61018735]]
[[0.11448305]
 [0.26626005]
 [0.6192569 ]]
[[0.11706477]
 [0.26824988]
 [0.61468535]]
[[0.11577267]
 [0.26726008]
 [0.61696725]]
[[0.11642005]
 [0.2677575 ]
 [0.61582245]]
[[0.11609586]
 [0.26750879]
 [0.61639535]]
[[0.11625825]
 [0.26763346]
 [0.61610829]]
[[0.11617692]
 [0.26757104]
 [0.61625204]]
[[0.11621765]
 [0.26760231]
 [0.61

In [75]:
print(realY)

[[0.1]
 [0.3]
 [0.6]]


In [ ]:
print("this is for iteration: ", iterations)
z1 = inputt.dot(w1) + b1
a1 = relu(z1)
z2 = a1.dot(w2) + b2
a2 = relu(z2)
z3 = a2.dot(w3) + b3
a3 = softmax(z3)
print(a3)

this is for iteration:  17
[[0.11620492]
 [0.26759254]
 [0.61620255]]


In [77]:
print(np.sum(a3))

1.0
